language: ruby
rvm:
  - "1.8.7"
  - "1.9.2"
  - "1.9.3"
  - "2.0.0"
gemfile:
  - gemfiles/Gemfile.chef-11
  - gemfiles/Gemfile.chef-10
matrix:
  exclude:
    - rvm: 2.0.0
      gemfile: gemfiles/Gemfile.chef-10
    - rvm: 1.8.7
      gemfile: gemfiles/Gemfile.chef-11
script: bundle exec rspec spec